models/StudentsUploadHistory.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "students_upload_history".
 *
 * @property integer $students_upload_history_id
 * @property integer $user_id
 * @property integer $py_id
 * @property string $ip_address
 * @property string $client_details
 * @property string $uploaded_file
 * @property string $date_uploaded
 * @property string $upload_report
 */
class StudentsUploadHistory extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'students_upload_history';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id', 'cy_id','fy_id', 'ip_address', 'client_details', 'uploaded_file', 'upload_report'], 'required'],
            [['user_id', 'py_id'], 'integer'],
            [['date_uploaded'], 'safe'],
            [['upload_report'], 'string'],
            [['ip_address'], 'string', 'max' => 200],
            [['client_details', 'uploaded_file'], 'string', 'max' => 250]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'students_upload_history_id' => 'Students Upload History ID',
            'user_id' => 'User ID',
            'cy_id' => 'Class year',
             'fy_id' => 'Form year',
            'ip_address' => 'Ip Address',
            'client_details' => 'Client Details',
            'uploaded_file' => 'Uploaded File',
            'date_uploaded' => 'Date Uploaded',
            'upload_report' => 'Upload Report',
        ];
    }
}

controllers/StudentsUploadHistoryController.php
<?php

namespace app\controllers;

use Yii;
use app\models\StudentsUploadHistory;
use app\models\StudentsUploadHistorySearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * StudentsUploadHistoryController implements the CRUD actions for StudentsUploadHistory model.
 */
class StudentsUploadHistoryController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all StudentsUploadHistory models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new StudentsUploadHistorySearch;
        $dataProvider = $searchModel->search(Yii::$app->request->getQueryParams());

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);
    }
    
    
    
    
    public function actionGetUploadHistory($cy_id) {
        $this->layout = 'simple_layout';
        $condition = " cy_id = {$cy_id}";
        $searchModel = new StudentsUploadHistorySearch;
        $dataProvider = $searchModel->search(Yii::$app->request->getQueryParams(), $condition);
        return $this->render('view_students_upload_history', [
                    'dataProvider' => $dataProvider,
                    'searchModel' => $searchModel,
        ]);
    }
    
       public function actionGetUploadHistory2($fy_id) {
        $this->layout = 'simple_layout';
        $condition = " fy_id = {$fy_id}";
        $searchModel = new StudentsUploadHistorySearch;
        $dataProvider = $searchModel->search(Yii::$app->request->getQueryParams(), $condition);
        return $this->render('view_students_upload_history', [
                    'dataProvider' => $dataProvider,
                    'searchModel' => $searchModel,
        ]);
    }

    public function actionUploadReport($students_upload_history_id) {
        header("Content-Type:   application/vnd.ms-excel; charset=utf-8");
        header("Content-Disposition: attachment; filename=upload_report.xls");  //File name extension was wrong
        header("Expires: 0");
        header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
        header("Cache-Control: private", false);
        $model_report = StudentsUploadHistory::findOne($students_upload_history_id);
        echo $model_report->upload_report;
        exit();
    }

    /**
     * Displays a single StudentsUploadHistory model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
        return $this->redirect(['view', 'id' => $model->students_upload_history_id]);
        } else {
        return $this->render('view', ['model' => $model]);
}
    }

    /**
     * Creates a new StudentsUploadHistory model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new StudentsUploadHistory;

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->students_upload_history_id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing StudentsUploadHistory model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->students_upload_history_id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing StudentsUploadHistory model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the StudentsUploadHistory model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return StudentsUploadHistory the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = StudentsUploadHistory::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/students-upload-history/_form.php
<?php

use yii\helpers\Html;
use kartik\widgets\ActiveForm;
use kartik\builder\Form;
use kartik\datecontrol\DateControl;

/**
 * @var yii\web\View $this
 * @var app\models\StudentsUploadHistory $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="students-upload-history-form">

    <?php $form = ActiveForm::begin(['type'=>ActiveForm::TYPE_HORIZONTAL]); echo Form::widget([

    'model' => $model,
    'form' => $form,
    'columns' => 1,
    'attributes' => [

'user_id'=>['type'=> Form::INPUT_TEXT, 'options'=>['placeholder'=>'Enter User ID...']], 

'py_id'=>['type'=> Form::INPUT_TEXT, 'options'=>['placeholder'=>'Enter Py ID...']], 

'ip_address'=>['type'=> Form::INPUT_TEXT, 'options'=>['placeholder'=>'Enter Ip Address...', 'maxlength'=>200]], 

'client_details'=>['type'=> Form::INPUT_TEXT, 'options'=>['placeholder'=>'Enter Client Details...', 'maxlength'=>250]], 

'uploaded_file'=>['type'=> Form::INPUT_TEXT, 'options'=>['placeholder'=>'Enter Uploaded File...', 'maxlength'=>250]], 

'upload_report'=>['type'=> Form::INPUT_TEXTAREA, 'options'=>['placeholder'=>'Enter Upload Report...','rows'=> 6]], 

'date_uploaded'=>['type'=> Form::INPUT_WIDGET, 'widgetClass'=>DateControl::classname(),'options'=>['type'=>DateControl::FORMAT_DATETIME]], 

    ]


    ]);
    echo Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']);
    ActiveForm::end(); ?>

</div>

views/students-upload-history/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var yii\web\View $this
 * @var app\models\StudentsUploadHistorySearch $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="students-upload-history-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'students_upload_history_id') ?>

    <?= $form->field($model, 'user_id') ?>

    <?= $form->field($model, 'py_id') ?>

    <?= $form->field($model, 'ip_address') ?>

    <?= $form->field($model, 'client_details') ?>

    <?php // echo $form->field($model, 'uploaded_file') ?>

    <?php // echo $form->field($model, 'date_uploaded') ?>

    <?php // echo $form->field($model, 'upload_report') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/students-upload-history/create.php
<?php

use yii\helpers\Html;

/**
 * @var yii\web\View $this
 * @var app\models\StudentsUploadHistory $model
 */

$this->title = 'Create Students Upload History';
$this->params['breadcrumbs'][] = ['label' => 'Students Upload Histories', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="students-upload-history-create">
    <div class="page-header">
        <h1><?= Html::encode($this->title) ?></h1>
    </div>
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/students-upload-history/index.php
<?php

use yii\helpers\Html;
use kartik\grid\GridView;
use yii\widgets\Pjax;

/**
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var app\models\StudentsUploadHistorySearch $searchModel
 */

$this->title = 'Students Upload Histories';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="students-upload-history-index">
    <div class="page-header">
            <h1><?= Html::encode($this->title) ?></h1>
    </div>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?php /* echo Html::a('Create Students Upload History', ['create'], ['class' => 'btn btn-success'])*/  ?>
    </p>

    <?php Pjax::begin(); echo GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'students_upload_history_id',
            'user_id',
            'py_id',
            'ip_address',
            'client_details',
//            'uploaded_file', 
//            ['attribute'=>'date_uploaded','format'=>['datetime',(isset(Yii::$app->modules['datecontrol']['displaySettings']['datetime'])) ? Yii::$app->modules['datecontrol']['displaySettings']['datetime'] : 'd-m-Y H:i:s A']], 
//            'upload_report:ntext', 

            [
                'class' => 'yii\grid\ActionColumn',
                'buttons' => [
                'update' => function ($url, $model) {
                                    return Html::a('<span class="glyphicon glyphicon-pencil"></span>', Yii::$app->urlManager->createUrl(['students-upload-history/view','id' => $model->students_upload_history_id,'edit'=>'t']), [
                                                    'title' => Yii::t('yii', 'Edit'),
                                                  ]);}

                ],
            ],
        ],
        'responsive'=>true,
        'hover'=>true,
        'condensed'=>true,
        'floatHeader'=>true,




        'panel' => [
            'heading'=>'<h3 class="panel-title"><i class="glyphicon glyphicon-th-list"></i> '.Html::encode($this->title).' </h3>',
            'type'=>'info',
            'before'=>Html::a('<i class="glyphicon glyphicon-plus"></i> Add', ['create'], ['class' => 'btn btn-success']),                                                                                                                                                          'after'=>Html::a('<i class="glyphicon glyphicon-repeat"></i> Reset List', ['index'], ['class' => 'btn btn-info']),
            'showFooter'=>false
        ],
    ]); Pjax::end(); ?>

</div>

views/students-upload-history/update.php
<?php

use yii\helpers\Html;

/**
 * @var yii\web\View $this
 * @var app\models\StudentsUploadHistory $model
 */

$this->title = 'Update Students Upload History: ' . ' ' . $model->students_upload_history_id;
$this->params['breadcrumbs'][] = ['label' => 'Students Upload Histories', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->students_upload_history_id, 'url' => ['view', 'id' => $model->students_upload_history_id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="students-upload-history-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/students-upload-history/view.php
<?php

use yii\helpers\Html;
use kartik\detail\DetailView;
use kartik\datecontrol\DateControl;

/**
 * @var yii\web\View $this
 * @var app\models\StudentsUploadHistory $model
 */

$this->title = $model->students_upload_history_id;
$this->params['breadcrumbs'][] = ['label' => 'Students Upload Histories', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="students-upload-history-view">
    <div class="page-header">
        <h1><?= Html::encode($this->title) ?></h1>
    </div>


    <?= DetailView::widget([
            'model' => $model,
            'condensed'=>false,
            'hover'=>true,
            'mode'=>Yii::$app->request->get('edit')=='t' ? DetailView::MODE_EDIT : DetailView::MODE_VIEW,
            'panel'=>[
            'heading'=>$this->title,
            'type'=>DetailView::TYPE_INFO,
        ],
        'attributes' => [
            'students_upload_history_id',
            'user_id',
            'py_id',
            'ip_address',
            'client_details',
            'uploaded_file',
            [
                'attribute'=>'date_uploaded',
                'format'=>['datetime',(isset(Yii::$app->modules['datecontrol']['displaySettings']['datetime'])) ? Yii::$app->modules['datecontrol']['displaySettings']['datetime'] : 'd-m-Y H:i:s A'],
                'type'=>DetailView::INPUT_WIDGET,
                'widgetOptions'=> [
                    'class'=>DateControl::classname(),
                    'type'=>DateControl::FORMAT_DATETIME
                ]
            ],
            'upload_report:ntext',
        ],
        'deleteOptions'=>[
        'url'=>['delete', 'id' => $model->students_upload_history_id],
        'data'=>[
        'confirm'=>Yii::t('app', 'Are you sure you want to delete this item?'),
        'method'=>'post',
        ],
        ],
        'enableEditMode'=>true,
    ]) ?>

</div>

views/students-upload-history/view_students_upload_history.php
<?php

use yii\helpers\Html;
use kartik\grid\GridView;
use yii\widgets\Pjax;

/**
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var app\models\StudentsUploadHistorySearch $searchModel
 */

$this->title = 'Students Upload History';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="students-upload-history-index">
  

    <?php Pjax::begin(); echo GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            //'students_upload_history_id',
//            'user_id',
                [
                'attribute' => 'user_id',
                'label' => 'User',
                'value' => function ($model) {
                    return app\models\Users::findOne($model->user_id)->firstname . ' ' . app\models\Users::findOne($model->user_id)->middlename . ' ' . app\models\Users::findOne($model->user_id)->surname;
                }
            ],
                    
            //'py_id',
            'ip_address',
            'client_details',
       [
                'label' => 'Download',
                'attribute' => 'uploaded_file',
                'value' => function($model) {
                    if ($model->uploaded_file == NULL) {
                        return '-';
                    } else {
                        return Html::a('Download', '' . $model->uploaded_file);
                    }
                },
                'format' => 'raw',
            ],
            [
                'label' => 'Report',
                'attribute' => 'upload_report',
                'value' => function($model) {
                    if ($model->upload_report == NULL) {
                        return '-';
                    } else {
                        return Html::a('Download', Yii::$app->urlManager->createUrl(['students-upload-history/upload-report', 'students_upload_history_id' => $model->students_upload_history_id,]), [
                        ]);
                        // return Html::a('Download', '' . $model->upload_report);
                    }
                },
                        'format' => 'raw',
                    ],
//            'uploaded_file', 
//            ['attribute'=>'date_uploaded','format'=>['datetime',(isset(Yii::$app->modules['datecontrol']['displaySettings']['datetime'])) ? Yii::$app->modules['datecontrol']['displaySettings']['datetime'] : 'd-m-Y H:i:s A']], 
//            'upload_report:ntext', 

//            [
//                'class' => 'yii\grid\ActionColumn',
//                'buttons' => [
//                'update' => function ($url, $model) {
//                                    return Html::a('<span class="glyphicon glyphicon-pencil"></span>', Yii::$app->urlManager->createUrl(['students-upload-history/view','id' => $model->students_upload_history_id,'edit'=>'t']), [
//                                                    'title' => Yii::t('yii', 'Edit'),
//                                                  ]);}
//
//                ],
//            ],
        ],
        'responsive'=>true,
        'hover'=>true,
        'condensed'=>true,
        'floatHeader'=>false,




        'panel' => [
            'heading'=>' ',
            'type'=>'default',
           // 'before'=>Html::a('<i class="glyphicon glyphicon-plus"></i> Add', ['create'], ['class' => 'btn btn-success']),                                                                                                                                                          'after'=>Html::a('<i class="glyphicon glyphicon-repeat"></i> Reset List', ['index'], ['class' => 'btn btn-info']),
            'showFooter'=>false
        ],
    ]); Pjax::end(); ?>

</div>